package work.parts.utils

object Common {
    val USER_ID: String = "id_user"
    val COSTS: String = "costs"
    val KM: String = "km"
    val COMMENT: String = "comment"
    val WORK_DONE: String = "work_done"
    val WORKING_TIME: String = "working_time"
    val DATA_TIME: String = "data_time"
    val PART_ID: String = "part_id"
    val PARTS: String = "p"
    val EMPLOYEE_ID: String = "employee_id"
    val WORK_ID: String = "work_id"
    val WORK_NAME: String = "work_name"
    val NONE: String = "none"
    val TAG: String = "tag"
    val WORK: String = "work"
    val COMPANY_ID: String = "company_id"
    val EMPLOYEE_PASSWORD: String = "employee_password"
    val EMPLOYEE_EMAIL: String = "employee_email"
    val EMPLOYEE_NAME: String = "employee_name"
    val EMPLOYEE: String = "employee"
    val COMPANY: String = "company"
    val UID: String = "uid"
    val COMPANY_NAME: String = "company_name"
    val COMPANY_EMAIL: String = "company_email"
    val COMPANY_PASSWORD: String = "company_password"
}